sudo: false

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - npm install -g grunt-cli

install:
  - bundle install
  - npm install grunt grunt-html --save-dev

# environment
language: ruby
rvm:
  - "2.2.3"
jdk:
  - oraclejdk8
dist: precise

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

notifications:
  email: false
