sudo: false

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - npm install -g grunt-cli

install:
  - bundle install
  - npm install grunt grunt-html --save-dev

# environment
language: ruby
rvm:
  - 2.2.3
jdk:
  - oraclejdk8
dist: precise

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

before_deploy: if [[ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} != master ]]; then
  bundle exec jekyll clean && bundle exec jekyll build --baseurl /root/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH};
  else
  bundle exec jekyll clean && bundle exec jekyll build;
  fi

deploy:
  - provider: s3
    access_key_id:
      secure: CywKj2zHq2LdODzlQ+bcBEhsKSCZS2twoWTAxP3dn2r5sm4zitjBJ07EmO/wqyw6HjlhAMdYV5LHIWKry+ytFT5QSFtC58jwNkZa9xj0NYleDcerePJOA5m6PfKoCePYcKYfovYv0LwRfHDjUcnPSq5L5syx+hzngbwF4NCJ0KeCE+v3BDiZrYvzuciDgfNEnmu/IYDgneBEcAhXTY4afVjsm0KI0OqIJ4rWp98u8eWCrsly/EXO1+tOU/Cesf8HyB5/bO+VAMd0GG3CtYKfPYkBSgcTmFru4OOsVIXx6eSQxfEcPRYNBYN3VxlauMnKhbssD5rrrNJafbmM7NQMQlFpp8LdzRuys4Lf5qOPXxHoTDjLLqDN9v4pCtV2GP0BX4LfOexy+DcAQe2FQv3BTgYNBmf6CHfzM01jZ9uHxdGvMZRxhD97jsmd7R4Cce3o96miOKQVbZZurjku1BP/vN3yX6ZEa2j7Yr+WnWCriemiN+47yCZQxriukhmrZVRqWCReU6iPcND7ovlKdciqT9Nf4MjM5D5rt8laIT1pC7fkGR1jSjJR5t8lkEv/D7lVXZsVpNuUZ1ennNnNav/RcA6UXt172DgKO4QuzYpaR9VQcl7AFU5xtF9u3Q6aflTUBu3UvxM4bQG+ZZliB6jMCW6HiuaZhsqVc2SIlcVveZU=
    secret_access_key:
      secure: Nu7H6aQ46yYwjvG/uFXkBFlsx79sNwMrjfQs7s2vcQKFq93RMo+hk61XOxGsox7BE/RWZlm1x7itPgb3j6hgtStTRzYb+aO3AugWf/wxTnUy2ZfCeDwCE0CQLRCdbVa3y1StClp8m4PRddpALjEsyGWkRkWDB+vTxWSAaBMRKmmzKRixA5nbhcwZq/mjy2SDQ21gBhSbZDj6czHz9NAsj89b3U0JL8AoKXnE4HtNlO491hA61W2FUFmnSJmLLmksLWiyC6TzGW8uR50Cj1nq32+82xjq4nUX4Uf300Ykkyz405AdnvnLZz+uz3ZBGjXiYXKsa1AnzRW/raBZ8KUjFY4peXrDj0ZgLHYa/8GI/KGNSyMx9M1GtUxMW5w/7HXoXBcIvfeC9wMLvKWH9tVVizpn+omP0lbz1AGph/oKG7rALU6hSJHcxmrBGkVahwZqkm+/znJgdiQxmMnOgYxUjlMYGYbBwWXQ9rzSXAx35k4DU1CsnokDZUvsWjw33xXT3I6W/GGmsjrSde1Y6ivXrkvHYqUIuqV18zAlSN9MXOgu0Rgm5ivvB9Zm7cKZW1Z8TFUIM9R3gnqpV/ExMwgYgDVGVP/90+Cmxr0Gcn5flVMwnztymt5lSDv7ZyuvnXAHwJGXiuziWxzbyf2cvMv2ZLiY8JdkwQzCDfL2dN2Vj84=
    bucket: root-website
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: _site
    on:
      branch: master
  - provider: s3
    access_key_id:
      secure: Ic/0CWr/MWOr1YAs2E1RPavSTNJRnGCuJv8E49Bq4d5ETX941zr6eafgp95HldosNhVCDcBxQS7okFQb6MSpy6hKyDfL9c4EHgsg1CyKbsUx9kmAizp73jzYHEB79usHc/2ofzz2PoMRr4kzotqHBqf/MRUbFWKqlkS8ZB7VUP6PDThEcVYNAmXf1lqUxBtcV1tHbQ/3AY/YEh4Oq3/dWE/fwATLosk7yRKOqjak25q9YIWZzW/KE+A/W39/COANmlAvfCg0ESa+jMjnrtnx4LcN7kzcWfGhgOitB6z3wNu584pIJICn6vpWaeBE+y/vZqWluy9eoGErWie5bybQKiPaXtafQfsf/RA/bY2qPwfnJo4+2WsDfwbw2D3NzKDSCvM/g4cm2qBCNKQjD4QsE+Q8rzT1kQj9gimls6mA54HegaKJ1TUngViNUJzyGTvamSXXeOMGa6Q81TzhJPizmOf9rkeIbjULxXaG4gQFEHuFkG8ws2/ZUvu3dQNnfWcCAb3H0FH2eiHAY1w4VGcsSEq88ku6A6EQCZYxgiEJzvwxijVu92SxL66KrZxl7nH1o9JZ4Nt0sm10ERe9eeyvNSQdDUZdMUT1dV0RTon2ZZ5TVA7JSV0+e5bajzSyfhanY8lIBSMGL/st1YJ2yVfv5CzSjPKIDL003nLaWEbdMuk=
    secret_access_key:
      secure: YWiwlOAAT0OmK1HS+HoHSrGazBngCSjazbDANaZcf8TEGn2wXcbm5n/Dm7vr/dwShbh3Dlzd5g94b2aQjWteESnPUfN3U1K9MBC0WIwovf77Xw5PoUEvBYoI5jcE6V3JziFkSlg3Ccr4dobe0sXkNqG56UCwm/hHWlpzaLU4rO5+ANCEPzFR6/kQilT9B1gicG7zIiW3jS1KEnTEHIijorB4me2iYjq2Ez+2E7jypgeA9hcznLOFzTfegKpVDIoNRtuWPAsNJLQ9fEHVQU1fJDWA/IgwDnOQlCBl14+Ky1aKiJsw1J6IEkcRpqo6yPqhF7glR+ThD/Tqn8Lv+dL3+MKKOab/vlqlnRizS6AvYb+kUsrvPtm+gxnJsVpeHL0LLZtPsi9B18PhFiNjUMcX1wXOLAwfXZZtigyNSG1mUnYcelSdNUb6YHKZzTGSTw47v/vadnSR6UcgbkPOWe7gZTY2WeZKG7jJt+kZbcyDXf45QRk93DuFq/o8uu31MUxSvutdcddCugDdK1wG9wksfxhgD1LnZV31PfzVRu3NOlN1vhonnXDcZNhcUH2creDYQxCmnQ8VzU6P7vQMGCUTnUFrPJ6ax8Pz7gH21LwzNh0NR8mLcCRIqSl/VwSv2to69owdam3GyQxtgBZ4QiHdl1R3YYk6wcq8bkQ8xs2zxuQ=
    bucket: preview-website
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: _site
    upload-dir: "root/$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH != master"

notifications:
  email: false
